logging:
  file:
    name: ${MW_LOG_DIR:/opt/mqtt_wol/logs}/log.log
  level:
    root: ${MW_LOG_LEVEL:INFO}
mqtt:
  server_uri: ${MW_MQTT_SERVER_URI:tcp://bemfa.com:9501}
  client_id: ${MW_MQTT_CLIENT_ID:cba8e6b25bb2ad84b9ad132fa8364b83}
  version: ${MW_MQTT_VERSION:3}
  topic: ${MW_MQTT_TOPIC:pc006}
wol:
  address: ${MW_WOL_ADDRESS:192.168.1.10}
  mac_address: ${MW_WOL_MAC_ADDRESS:E8:9C:22:BB:44:A4}
winrm:
  address: ${MW_WINRM_ADDRESS:192.168.1.10}
  port: ${MW_WINRM_PORT:5985}
  username: ${MW_WINRM_USERNAME:winrm}
  password: ${MW_WINRM_PASSWORD:pa55w0rd!}
