spring:
  application:
    name: mqtt-wol
  profiles:
    active: default
  main:
    web-application-type: none
  config:
    # Configuration file path
    import: optional:file:${CA_CONFIG_FILE:/opt/mqtt_wol/conf.properties}
  threads:
    virtual:
      enabled: true
