logging:
  file:
    name: ${MW_LOG_DIR:/opt/mqtt_wol/logs}/log.log
  level:
    root: ${MW_LOG_LEVEL:INFO}
mqtt:
  client_id: ${MW_MQTT_CLIENT_ID:cba8e6b25bb2ad84b9ad132fa8364b83}
  server_host: ${MW_MQTT_SERVER_HOST:bemfa.com}
  server_port: ${MW_MQTT_SERVER_PORT:9503}
  server_ssl: ${MW_MQTT_SERVER_SSL:true}
  topic: ${MW_MQTT_TOPIC:pc006}
wol:
  address: ${MW_WOL_ADDRESS:192.168.1.10}
  mac_address: ${MW_WOL_MAC_ADDRESS:E8:9C:22:BB:44:A4}
winrm:
  address: ${MW_WINRM_ADDRESS:192.168.1.10}
  port: ${MW_WINRM_PORT:5985}
  username: ${MW_WINRM_USERNAME:winrm}
  password: ${MW_WINRM_PASSWORD:pa55w0rd!}
