# The default path for this configuration file is: /opt/mqtt_wol/conf.properties
# Or inject the following parameters by using environment variables

# Log configuration
ca_log_dir=/opt/mqtt_wol/logs
ca_log_level=INFO

# MQTT configuration
mqtt_server_uri=tcp://bemfa.com:9501
mqtt_client_id=cba8e6b25bb2ad84b9ad132fa8364b83
mqtt_version=3
mqtt_topic=pc006

# WOL configuration
# IP or domain
wol_address=192.168.1.10
# xx:xx or xx-xx or xxxx.xxxx
wol_mac_address=E8:9C:22:BB:44:A4

WinRM configuration
# IP or domain
winrm_address=192.168.1.10
winrm_port=5985
winrm_username=winrm
winrm_password=pa55w0rd!
