# The default path for this configuration file is: /opt/mqtt_wol/conf.properties
# Or inject the following parameters by using environment variables

# Log configuration
MW_LOG_DIR=/opt/mqtt_wol/logs
MW_LOG_LEVEL=INFO

# MQTT configuration
MW_MQTT_CLIENT_ID=cba8e6b25bb2ad84b9ad132fa8364b83
MW_MQTT_SERVER_HOST=bemfa.com
MW_MQTT_SERVER_PORT=9503
MW_MQTT_SERVER_SSL=true
MW_MQTT_TOPIC=pc006

# WOL configuration
# IP or domain
MW_WOL_ADDRESS=192.168.1.10
# xx:xx or xx-xx or xxxx.xxxx
MW_WOL_MAC_ADDRESS=E8:9C:22:BB:44:A4

WinRM configuration
# IP or domain
MW_WINRM_ADDRESS=192.168.1.10
MW_WINRM_PORT=5985
MW_WINRM_USERNAME=winrm
MW_WINRM_PASSWORD=pa55w0rd!
